import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { SOCIAL_CARDS, socialCardFor, structuredData, SITE_ORIGIN, SECURITY_CONTACT, REPO_URL } from '../siteMeta';
import { securityTxt } from '../../scripts/build-security-txt.mjs';
import { SECTIONS as VC } from '../modules/voice-cloning';
import { SECTIONS as VA } from '../modules/voice-agents';
import { SECTIONS as SE } from '../modules/social-engineering';
import { SECTIONS as AP } from '../modules/appendix';

// Deliberately not a second copy of the origin string — siteMeta.js is the one
// source of truth, and a hardcoded duplicate here silently stops testing
// anything the moment the real origin changes.
const ORIGIN = SITE_ORIGIN;

const MODULES = {
  'voice-cloning': VC,
  'voice-agents': VA,
  'social-engineering': SE,
  appendix: AP,
};

const expectedRoutes = Object.entries(MODULES)
  .flatMap(([slug, sections]) => sections.map(s => `/${slug}/${s.id}`))
  .concat('/quiz');

// Vitest runs from the project root.
const read = (p) => readFileSync(join(process.cwd(), p), 'utf8');

// These files are hand-maintained but must track the SECTIONS arrays. Without a
// test they rot silently the first time somebody adds a section.
describe('sitemap.xml', () => {
  const sitemap = read('public/sitemap.xml');
  const locs = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m => m[1]);

  it('lists every route', () => {
    const missing = expectedRoutes.filter(r => !locs.includes(`${ORIGIN}${r}`));
    expect(missing).toEqual([]);
  });

  it('lists no route that does not exist', () => {
    const extra = locs
      .map(l => l.replace(ORIGIN, ''))
      .filter(p => p !== '/' && !expectedRoutes.includes(p));
    expect(extra).toEqual([]);
  });

  it('includes the site root', () => {
    expect(locs).toContain(`${ORIGIN}/`);
  });
});

describe('netlify.toml', () => {
  const toml = read('netlify.toml');

  // The SPA rewrite is scoped per module so unknown URLs get a real 404. That
  // means a new module needs a rule here or its deep links 404 in production.
  it('has an SPA rewrite for every module', () => {
    const missing = Object.keys(MODULES).filter(slug => !toml.includes(`from = "/${slug}/*"`));
    expect(missing).toEqual([]);
  });

  it('falls through to a real 404', () => {
    expect(toml).toContain('to = "/404.html"');
    expect(toml).toContain('status = 404');
  });

  it('does not set HSTS (that belongs at the Cloudflare edge)', () => {
    expect(toml).not.toContain('Strict-Transport-Security');
  });
});

describe('robots.txt', () => {
  it('points at the sitemap', () => {
    expect(read('public/robots.txt')).toContain(`Sitemap: ${ORIGIN}/sitemap.xml`);
  });
});

// The cards are generated by scripts/build-og-images.py and committed, so
// nothing at build time would notice a missing or mis-sized file — a scraper
// would just show a broken preview.
describe('social cards', () => {
  const cardKeys = Object.keys(SOCIAL_CARDS);

  it('has a card for every module', () => {
    const missing = Object.keys(MODULES).filter(slug => !cardKeys.includes(slug));
    expect(missing).toEqual([]);
  });

  it('has a default card and a quiz card', () => {
    expect(cardKeys).toContain('default');
    expect(cardKeys).toContain('quiz');
  });

  it.each(cardKeys)('%s: the image file exists', (key) => {
    expect(existsSync(join(process.cwd(), 'public', SOCIAL_CARDS[key].image))).toBe(true);
  });

  // Facebook, LinkedIn, Slack and X all key off 1200x630; anything else is
  // cropped or letterboxed by at least one of them.
  it.each(cardKeys)('%s: the image is a 1200x630 PNG', (key) => {
    const buf = readFileSync(join(process.cwd(), 'public', SOCIAL_CARDS[key].image));
    expect(buf.subarray(1, 4).toString()).toBe('PNG');
    expect([buf.readUInt32BE(16), buf.readUInt32BE(20)]).toEqual([1200, 630]);
  });

  it.each(cardKeys)('%s: has non-empty alt text', (key) => {
    expect(SOCIAL_CARDS[key].alt.length).toBeGreaterThan(0);
  });

  it('resolves image URLs to absolute ones', () => {
    // A relative og:image is treated as missing by every scraper.
    expect(socialCardFor('voice-cloning').image).toBe(`${SITE_ORIGIN}/images/og-voice-cloning.png`);
  });

  it('falls back to the default card for an unknown key', () => {
    expect(socialCardFor('nope').image).toBe(`${SITE_ORIGIN}/images/og-card.png`);
  });
});

describe('structured data', () => {
  const url = `${SITE_ORIGIN}/voice-cloning/intro`;
  const graph = structuredData({
    url,
    title: 'Introduction — Voice Cloning | Call Center Village',
    description: 'desc',
    image: `${SITE_ORIGIN}/images/og-voice-cloning.png`,
    breadcrumbs: [
      { name: 'Call Center Village', url: `${SITE_ORIGIN}/` },
      { name: 'Voice Cloning', url },
    ],
  })['@graph'];

  const byType = (type) => graph.find(node => node['@type'] === type);

  it('names the author', () => {
    expect(byType('Person').name).toBe('Patrick Labbett');
  });

  it('names the publishing organisation with its other profiles', () => {
    const org = byType('Organization');
    expect(org.name).toBe('Call Center Village');
    expect(org.sameAs).toContain('https://defcon.social/@callcentervillage');
  });

  // Referencing by @id rather than inlining is what lets a consumer tell it is
  // the same person and the same site across pages.
  it('points the page at the author, publisher and site by reference', () => {
    const page = byType('WebPage');
    expect(page.author).toEqual({ '@id': `${SITE_ORIGIN}/#author` });
    expect(page.publisher).toEqual({ '@id': `${SITE_ORIGIN}/#organization` });
    expect(page.isPartOf).toEqual({ '@id': `${SITE_ORIGIN}/#website` });
    expect(graph.some(n => n['@id'] === page.author['@id'])).toBe(true);
    expect(graph.some(n => n['@id'] === page.publisher['@id'])).toBe(true);
  });

  it('numbers breadcrumbs from 1', () => {
    expect(byType('BreadcrumbList').itemListElement.map(i => i.position)).toEqual([1, 2]);
  });

  it('omits the breadcrumb entirely when there is no trail', () => {
    const bare = structuredData({ url, title: 't', description: 'd', image: 'i' })['@graph'];
    expect(bare.find(n => n['@type'] === 'BreadcrumbList')).toBeUndefined();
    expect(bare.find(n => n['@type'] === 'WebPage').breadcrumb).toBeUndefined();
  });
});

describe('index.html head', () => {
  const html = read('index.html');

  // scripts/prerender.mjs rewrites everything between these and throws if they
  // are gone, which would fail the build — but only after a full vite build.
  it('keeps the markers the prerenderer replaces', () => {
    expect(html).toContain('<!-- social:start -->');
    expect(html).toContain('<!-- social:end -->');
  });

  it.each([
    ['author', '<meta name="author" content="Patrick Labbett" />'],
    ['og:site_name', '<meta property="og:site_name" content="Call Center Village" />'],
    ['og:image:alt', 'property="og:image:alt"'],
    ['twitter:image:alt', 'name="twitter:image:alt"'],
    ['fediverse:creator', 'content="@callcentervillage@defcon.social"'],
  ])('carries %s in the static fallback', (_label, snippet) => {
    expect(html).toContain(snippet);
  });

  it('has JSON-LD that parses and credits the author', () => {
    const match = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
    expect(match).toBeTruthy();
    const graph = JSON.parse(match[1])['@graph'];
    expect(graph.find(n => n['@type'] === 'Person').name).toBe('Patrick Labbett');
  });
});

describe('security.txt', () => {
  const txt = read('public/.well-known/security.txt');
  const field = (name) => txt.match(new RegExp(`^${name}: (.+)$`, 'm'))?.[1];

  it('has the contact from siteMeta', () => {
    expect(field('Contact')).toBe(`mailto:${SECURITY_CONTACT}`);
  });

  it('points its canonical at this site', () => {
    expect(field('Canonical')).toBe(`${ORIGIN}/.well-known/security.txt`);
  });

  // RFC 9116 requires Expires, and an expired file is treated as invalid. The
  // committed copy is regenerated by `pnpm build`, so this failing means nobody
  // has built in a year: run `pnpm build:security` and commit the result.
  it('has an Expires date in the future', () => {
    expect(new Date(field('Expires')).getTime()).toBeGreaterThan(Date.now());
  });
});

// The generator, not the file it last wrote. Pinning the output against a fixed
// clock is the only way to test the Expires rule without waiting a year.
describe('build-security-txt', () => {
  const txt = securityTxt(new Date('2026-01-15T10:00:00.000Z'));
  const field = (name) => txt.match(new RegExp(`^${name}: (.+)$`, 'm'))?.[1];

  it('expires less than a year after the build', () => {
    const expires = new Date(field('Expires')).getTime();
    const built = new Date('2026-01-15T10:00:00.000Z').getTime();
    expect(expires).toBeGreaterThan(built);
    expect(expires - built).toBeLessThan(366 * 24 * 60 * 60 * 1000);
  });

  it('writes an RFC 9116 timestamp', () => {
    expect(field('Expires')).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.000Z$/);
  });

  it('carries the contact, canonical and policy fields', () => {
    expect(field('Contact')).toBe(`mailto:${SECURITY_CONTACT}`);
    expect(field('Canonical')).toBe(`${ORIGIN}/.well-known/security.txt`);
    expect(field('Policy')).toBe(`${REPO_URL}/blob/main/SECURITY.md`);
  });
});
