import {
  MicrophoneIcon,
  ChartBarIcon,
  AdjustmentsHorizontalIcon,
  CpuChipIcon,
  ComputerDesktopIcon,
  CloudIcon,
  ShieldCheckIcon,
  BeakerIcon,
  CommandLineIcon,
  CubeIcon,
  SignalIcon,
  SpeakerWaveIcon,
  WrenchIcon,
  PhoneIcon,
  UserIcon,
  UserGroupIcon,
  ShieldExclamationIcon,
  ClockIcon,
  ArrowTrendingUpIcon,
  ClipboardDocumentListIcon,
  DocumentTextIcon,
  ArrowPathIcon,
  ArrowsRightLeftIcon,
  SpeakerXMarkIcon,
  MusicalNoteIcon,
  PencilSquareIcon,
  VariableIcon,
  BoltIcon,
  WrenchScrewdriverIcon,
  GlobeAltIcon,
  TrophyIcon,
  MagnifyingGlassIcon,
  PhoneArrowDownLeftIcon,
  CurrencyDollarIcon,
  CheckCircleIcon,
  XCircleIcon,
  ChevronDownIcon,
  Bars3Icon,
  XMarkIcon,
  ExclamationTriangleIcon,
  ChatBubbleLeftRightIcon,
  LockClosedIcon,
  HandRaisedIcon,
  StarIcon,
  EyeIcon,
  ScaleIcon,
  PresentationChartLineIcon,
  CodeBracketIcon,
  ServerIcon,
  ArrowRightIcon,
  PlayIcon,
  RocketLaunchIcon,
  HomeIcon,
  FireIcon,
  InformationCircleIcon,
  QuestionMarkCircleIcon,
  BookOpenIcon,
  AcademicCapIcon,
  FunnelIcon,
  GiftIcon,
  IdentificationIcon,
  BriefcaseIcon,
  FlagIcon,
  KeyIcon,
  LinkIcon,
  HashtagIcon,
  TableCellsIcon,
  PaintBrushIcon,
  SwatchIcon,
  FingerPrintIcon,
  BuildingOfficeIcon,
  ChartPieIcon,
  Cog6ToothIcon,
  ArrowDownTrayIcon,
  CircleStackIcon,
  HeartIcon,
  EyeSlashIcon,
} from "@heroicons/react/24/outline";

const iconMap = {
  // Section nav icons
  microphone: MicrophoneIcon,
  "chart-bar": ChartBarIcon,
  adjustments: AdjustmentsHorizontalIcon,
  cpu: CpuChipIcon,
  computer: ComputerDesktopIcon,
  cloud: CloudIcon,
  shield: ShieldCheckIcon,
  beaker: BeakerIcon,
  "command-line": CommandLineIcon,
  cube: CubeIcon,
  signal: SignalIcon,
  "speaker-wave": SpeakerWaveIcon,
  wrench: WrenchIcon,
  phone: PhoneIcon,
  user: UserIcon,
  "user-group": UserGroupIcon,
  "shield-exclamation": ShieldExclamationIcon,
  clock: ClockIcon,
  "trending-up": ArrowTrendingUpIcon,
  clipboard: ClipboardDocumentListIcon,
  document: DocumentTextIcon,
  "arrow-path": ArrowPathIcon,
  "arrows-right-left": ArrowsRightLeftIcon,
  "speaker-x": SpeakerXMarkIcon,
  headphones: MusicalNoteIcon,
  "musical-note": MusicalNoteIcon,
  pencil: PencilSquareIcon,
  variable: VariableIcon,
  bolt: BoltIcon,
  "wrench-screwdriver": WrenchScrewdriverIcon,
  globe: GlobeAltIcon,
  trophy: TrophyIcon,
  "magnifying-glass": MagnifyingGlassIcon,
  "phone-incoming": PhoneArrowDownLeftIcon,
  currency: CurrencyDollarIcon,
  "check-circle": CheckCircleIcon,
  "x-circle": XCircleIcon,
  "chevron-down": ChevronDownIcon,
  bars: Bars3Icon,
  "x-mark": XMarkIcon,
  warning: ExclamationTriangleIcon,
  chat: ChatBubbleLeftRightIcon,
  lock: LockClosedIcon,
  "hand-raised": HandRaisedIcon,
  star: StarIcon,
  eye: EyeIcon,
  scale: ScaleIcon,
  "chart-line": PresentationChartLineIcon,
  "code-bracket": CodeBracketIcon,
  server: ServerIcon,
  "arrow-right": ArrowRightIcon,
  play: PlayIcon,
  rocket: RocketLaunchIcon,
  home: HomeIcon,
  fire: FireIcon,
  info: InformationCircleIcon,
  question: QuestionMarkCircleIcon,
  book: BookOpenIcon,
  academic: AcademicCapIcon,
  funnel: FunnelIcon,
  gift: GiftIcon,
  identification: IdentificationIcon,
  briefcase: BriefcaseIcon,
  flag: FlagIcon,
  key: KeyIcon,
  link: LinkIcon,
  hashtag: HashtagIcon,
  table: TableCellsIcon,
  "paint-brush": PaintBrushIcon,
  swatch: SwatchIcon,
  fingerprint: FingerPrintIcon,
  building: BuildingOfficeIcon,
  "chart-pie": ChartPieIcon,
  cog: Cog6ToothIcon,
  download: ArrowDownTrayIcon,
  database: CircleStackIcon,
  heart: HeartIcon,
  "eye-slash": EyeSlashIcon,
};

const Icon = ({ name, size = 20, _className, style, ...props }) => {
  const IconComponent = iconMap[name];
  if (!IconComponent) return null;
  return (
    <IconComponent
      style={{ width: size, height: size, strokeWidth: 1.5, ...style }}
      aria-hidden="true"
      {...props}
    />
  );
};

export { Icon, iconMap };
export default Icon;
