/**
 * Identity and link-preview metadata, in one place.
 *
 * Three consumers read from here and they must not drift apart:
 *   - index.html          the static fallback (dev server, and any route that
 *                         somehow escapes prerendering)
 *   - scripts/prerender.mjs  rewrites the head per route at build time
 *   - src/App.jsx         keeps the tags honest after a client-side navigation
 *
 * Anything a scraper reads lives here rather than being typed into the HTML,
 * because a value that appears in only one of the three is a value that will be
 * wrong on some page.
 */

export const SITE_ORIGIN = "https://callcentervillage.org";
export const SITE_NAME = "Call Center Village";
export const LOCALE = "en_US";
export const LANGUAGE = "en-US";

export const DEFAULT_DESCRIPTION =
  "Free, hands-on training in voice security: AI voice cloning, voice agent " +
  "architecture and attack surface, and social engineering against humans and AI agents.";

/** Bylined author. Surfaces as <meta name="author">, article:author and schema.org Person. */
export const AUTHOR = { name: "Patrick Labbett" };

/** The village itself — publisher of the training, not the author of it. */
export const PUBLISHER = {
  name: SITE_NAME,
  url: "https://www.callcentervillage.com",
  logo: "/images/ccv-logo.png",
  logoSize: 200,
  sameAs: [
    "https://www.callcentervillage.com",
    "https://defcon.social/@callcentervillage",
  ],
};

/**
 * Mastodon 4.3+ reads this and renders "by @callcentervillage" on the preview
 * card, which is the fediverse equivalent of twitter:creator. There is no X
 * account, so twitter:site / twitter:creator are deliberately absent — an empty
 * or wrong handle there is worse than none.
 */
export const FEDIVERSE_CREATOR = "@callcentervillage@defcon.social";

export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;

/**
 * One card per module so a shared deep link says which module it points at.
 * Generated by scripts/build-og-images.py — the keys here are module slugs from
 * MODULES in App.jsx, and src/test/staticFiles.test.js asserts both that every
 * module has an entry and that every file referenced exists.
 */
export const SOCIAL_CARDS = {
  default: {
    image: "/images/og-card.png",
    alt: "Call Center Village — voice security training",
  },
  "voice-cloning": {
    image: "/images/og-voice-cloning.png",
    alt: "Voice Cloning — Call Center Village voice security training",
  },
  "voice-agents": {
    image: "/images/og-voice-agents.png",
    alt: "Voice Agents — Call Center Village voice security training",
  },
  "social-engineering": {
    image: "/images/og-social-engineering.png",
    alt: "Social Engineering — Call Center Village voice security training",
  },
  appendix: {
    image: "/images/og-appendix.png",
    alt: "Appendix — Call Center Village voice security training",
  },
  quiz: {
    image: "/images/og-quiz.png",
    alt: "Knowledge Test — Call Center Village voice security training",
  },
};

/** Absolute URL — scrapers treat a relative og:image as missing. */
export const absolute = (path) => `${SITE_ORIGIN}${path}`;

export function socialCardFor(key) {
  const card = SOCIAL_CARDS[key] ?? SOCIAL_CARDS.default;
  return { image: absolute(card.image), alt: card.alt };
}

/**
 * The schema.org graph for one page.
 *
 * Author and publisher are separate nodes referenced by @id rather than inlined,
 * so a consumer reading several pages can tell it is the same person and the
 * same organisation each time.
 */
export function structuredData({ url, title, description, image, breadcrumbs = [] }) {
  const graph = [
    {
      "@type": "Person",
      "@id": `${SITE_ORIGIN}/#author`,
      name: AUTHOR.name,
    },
    {
      "@type": "Organization",
      "@id": `${SITE_ORIGIN}/#organization`,
      name: PUBLISHER.name,
      url: PUBLISHER.url,
      logo: {
        "@type": "ImageObject",
        url: absolute(PUBLISHER.logo),
        width: PUBLISHER.logoSize,
        height: PUBLISHER.logoSize,
      },
      sameAs: PUBLISHER.sameAs,
    },
    {
      "@type": "WebSite",
      "@id": `${SITE_ORIGIN}/#website`,
      url: `${SITE_ORIGIN}/`,
      name: SITE_NAME,
      description: DEFAULT_DESCRIPTION,
      inLanguage: LANGUAGE,
      publisher: { "@id": `${SITE_ORIGIN}/#organization` },
    },
    {
      "@type": "WebPage",
      "@id": `${url}#webpage`,
      url,
      name: title,
      description,
      inLanguage: LANGUAGE,
      isPartOf: { "@id": `${SITE_ORIGIN}/#website` },
      author: { "@id": `${SITE_ORIGIN}/#author` },
      publisher: { "@id": `${SITE_ORIGIN}/#organization` },
      primaryImageOfPage: {
        "@type": "ImageObject",
        url: image,
        width: OG_IMAGE_WIDTH,
        height: OG_IMAGE_HEIGHT,
      },
      ...(breadcrumbs.length ? { breadcrumb: { "@id": `${url}#breadcrumb` } } : {}),
    },
  ];

  if (breadcrumbs.length) {
    graph.push({
      "@type": "BreadcrumbList",
      "@id": `${url}#breadcrumb`,
      itemListElement: breadcrumbs.map((crumb, i) => ({
        "@type": "ListItem",
        position: i + 1,
        name: crumb.name,
        item: crumb.url,
      })),
    });
  }

  return { "@context": "https://schema.org", "@graph": graph };
}
